AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Node.js implementation of four endpoints/Lambda functions for authorization code grant type using AWS Cognito and Lambda.

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100
    Tracing: Active
    Environment:
      Variables:
        COGNITO_DOMAIN_PREFIX: sunnyoauth
        COGNITO_APP_ID: 1vvp0tt53g1uhntoa5bmvnvk2a
        COGNITO_APP_SECRET: <secret>
        #API_GATEWAY_URL: https://mgbzy4msg9.execute-api.us-east-1.amazonaws.com/Prod/
        CORS_ALLOW_ORIGIN: http://localhost:4200
        #CORS_ALLOW_ORIGIN: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com
        LOGIN_REDIRECT_URL: http://localhost:4200
        #LOGIN_REDIRECT_URL: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com
        SESSION_TABLE: !Ref SessionTable
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  authenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/authentication-handler.authenticationHandler
      Description: Authentication endpoints to handle authorization code grant type using AWS Lambda, API Gateway and Cognito.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:GlobalSignOut
            Resource: "*"
      Events:
        DemoAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
