AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Node.js implementation of four endpoints/Lambda functions for authorization code grant type using AWS Cognito and Lambda.

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100
    Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
    Tracing: Active
    Environment:
      Variables:
        COGNITO_DOMAIN_PREFIX: sunnyoauth
        COGNITO_APP_ID: 1vvp0tt53g1uhntoa5bmvnvk2a
        COGNITO_APP_SECRET: <secret>
        #API_GATEWAY_URL: https://mgbzy4msg9.execute-api.us-east-1.amazonaws.com/Prod/
        CORS_ALLOW_ORIGIN: http://localhost:4200
        #CORS_ALLOW_ORIGIN: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com
        LOGIN_REDIRECT_URL: http://localhost:4200
        #LOGIN_REDIRECT_URL: http://oauthdemo2021.s3-website-us-east-1.amazonaws.com

Resources:

  getLoginUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-login-url.getLoginUrlHandler
      Description: Authentication endpoint to return login URL pointing to Cognito.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /authentication/login
            Method: GET
  getLoginStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-login-status.getLoginStatusHandler
      Description: Authentication endpoint to return current login status.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /authentication/status
            Method: GET
  logoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/logout.logoutHandler
      Description: Authentication endpoint to logout existing session.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /authentication/logout
            Method: GET
  exchangeCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/exchange-code.exchangeCodeHandler
      Description: Authentication endpoint to exchange code for a session token.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /authentication/exchange
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
